### ISSUE TITLE
m2e-wtp in 1.1 catalog not compatible with m2e 1.3

### ISSUE THREAD

**Issue by andham** [takari/m2e-discovery-catalog#20]
Tried to install m2e-wtp from the 1.1 discovery catalog (which m2e v1.3 uses) in Juno SR2, but it doesn't work. I think it's because it's m2e-wtp 1.0.0 that is listed which requires m2e 1.4.
We should change so that a m2e-wtp version compatible with m2e 1.1-1.3 is listed in this discovery catalog.

**Comment by hgschmie** [comment]
guess that is fixed.
