### ISSUE TITLE
mvn package isn't working due to undefined property

### ISSUE THREAD

**Issue by bimargulies** [takari/m2e-discovery-catalog#8]
[INFO] Total time: 2.865s
[INFO] Finished at: Sun Nov 04 17:11:53 EST 2012
[INFO] Final Memory: 7M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonatype.m2e.discovery.publisher:org.sonatype.m2e.discovery.publisher.maven-plugin:0.0.1-SNAPSHOT:generate (catalog) on project org.eclipse.m2e.discovery.oss: java.net.URISyntaxException: Illegal character in path at index 1: ${connectorUrl}/m2eclipse-tycho/0.6.0/N/0.6.0.201207302152/ -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.eclipse.m2e.discovery.oss

**Comment by hgschmie** [comment]
applied ages ago.
